### ISSUE TITLE
Minting Crewmates

### ISSUE THREAD

**Issue by MarkyB71** [influenceth/client#595]
I've noticed the past 3 Skippys that have minted on TRCS have caused the pesky Hopper to go rogue.
![image](https://github.com/user-attachments/assets/c0aa98bc-0d0a-4e99-aba8-39cb8ea4b3b5)

Once i refresh it's all working fine. just crashes when i complete the transaction.

If you need any other info please let me know.

**Comment by MarkyB71** [comment]
Definitely happening every time i mint new crew on The Real Club Skippy Leisure Potato Asteroid ID#
27963. I'm creating a crew called The Skippys (Like the Simpsons) So far Homer and Marge Skippy have caused the hoper to go rogue when confirming the transaction.
27964. 
![image](https://github.com/user-attachments/assets/5454f48d-b4cb-4cba-a195-2121b903dc35)
![image](https://github.com/user-attachments/assets/ca68101c-89b9-467e-bdd8-963983f1abc1)
![image](https://github.com/user-attachments/assets/05462588-efab-4753-9cb2-4edbd256d7fb)

**Comment by MarkyB71** [comment]
See thst's what happens when you assume only after 2 instances ;)
Bart Skippy did not crask the hoper this time 
![image](https://github.com/user-attachments/assets/42b0d189-9f7f-4362-ab88-4970fcbf7338)

**Comment by MarkyB71** [comment]
![image](https://github.com/user-attachments/assets/b9d7310c-89b0-4414-9fca-e4209bfc44d4)
So it was only Homer and Marge that caused the hopper to go rogue. It went rogue yesterday on 3 other crews i minted.

**Comment by MarkyB71** [comment]
One thing to note. I thought these were being minted on TRCS, i used an existing empty crew and had y habitat selected but the crew must have been in Proto's hab as they are all on bloody AP now 🤔. I'll fly them out but it's a bit of a pain when i minted them to start mining on TRCS.

**Comment by prof197** [comment]
This should have been fixed by https://github.com/influenceth/client/pull/594
